###############################################################
# Program:
#     Assignment 04, Product inventory
#     Brother Barney, CS165
# Author:
#     Zachary Caldwell
# Summary:
#     Create a Product object, fill it with user data, and
#     display it in the requested format.
#
#     Estimated:  1.5 hrs
#     Actual:     2.0 hrs
#       The hardest part was getting the display functions right and remembering
#       the fiddly cout options for formatting numbers.
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : product.h product.cpp assign04.cpp
	g++ product.cpp assign04.cpp

